default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

test:
  adapter: sqlite3
  encoding: unicode
  database: cyfer_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
